config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :operaciones_aereas
  resources :pilotos
  resources :usuarios
  resources :aeronaves
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "operaciones_aereas#new"
end

app/models/operaciones_aerea.rb
class OperacionesAerea < ApplicationRecord
  belongs_to :aeronave
  belongs_to :piloto

  after_create :update_piloto
  after_create :update_aeronave

  def update_piloto
    piloto.horas_vuelo += horas_vuelo
    piloto.save
  end

  def update_aeronave
    aeronave.horas_vuelo_mantencion += horas_vuelo
    aeronave.horas_vuelo_acumulado += horas_vuelo
    aeronave.save
  end

end

app/controllers/operaciones_aereas_controller.rb
class OperacionesAereasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_operaciones_aerea, only: %i[ show edit update destroy ]
  layout 'dashboard'

  # GET /operaciones_aereas or /operaciones_aereas.json
  def index
    @operaciones_aereas = OperacionesAerea.all
  end

  # GET /operaciones_aereas/1 or /operaciones_aereas/1.json
  def show
  end

  # GET /operaciones_aereas/new
  def new
    @operaciones_aerea = OperacionesAerea.new
    @aeronaves = Aeronave.all
  end

  # GET /operaciones_aereas/1/edit
  def edit
  end

  # POST /operaciones_aereas or /operaciones_aereas.json
  def create
    @operaciones_aerea = OperacionesAerea.new(operaciones_aerea_params)

    respond_to do |format|
      if @operaciones_aerea.save
        format.html { redirect_to new_operaciones_aerea_url, notice: "Operación aérea guardada con éxito." }
        format.json { render :new, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operaciones_aerea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operaciones_aereas/1 or /operaciones_aereas/1.json
  def update
    respond_to do |format|
      if @operaciones_aerea.update(operaciones_aerea_params)
        format.html { redirect_to operaciones_aerea_url(@operaciones_aerea), notice: "Operaciones aerea was successfully updated." }
        format.json { render :show, status: :ok, location: @operaciones_aerea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operaciones_aerea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operaciones_aereas/1 or /operaciones_aereas/1.json
  def destroy
    @operaciones_aerea.destroy

    respond_to do |format|
      format.html { redirect_to operaciones_aereas_url, notice: "Operaciones aerea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operaciones_aerea
      @operaciones_aerea = OperacionesAerea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operaciones_aerea_params
      params.require(:operaciones_aerea).permit(:aeronave_id, :piloto_id, :fecha_operacion, :horas_vuelo, :toque_y_despegue, :aterrizajes, :incidentes, :comentarios, :aerodromos)
    end
end

app/helpers/operaciones_aereas_helper.rb
module OperacionesAereasHelper
end

app/views/operaciones_aereas/_form.html.erb
<%= form_with(model: operaciones_aerea) do |form| %>
  <% if operaciones_aerea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operaciones_aerea.errors.count, "error") %> prohibited this operaciones_aerea from being saved:</h2>

      <ul>
        <% operaciones_aerea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :piloto_id, value: current_usuario.piloto&.id %>

  <div class="mb-6">
    <%= label_tag "Piloto al mando", nil, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= text_field_tag 'piloto_name', current_usuario.full_name, disabled: true, "aria-label":"disabled input", class: "bg-gray-50 border border-gray-300 text-gray-500 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 cursor-not-allowed dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :aeronave_id, "Matrícula de aeronave", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.collection_select :aeronave_id, @aeronaves, :id, :matricula, {prompt: "Selecciona la aeronave"}, {class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"} %>
  </div>
  <div class="mb-6">
    <%= form.label :fecha_operacion, "Fecha de la operación", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.date_field :fecha_operacion, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :horas_vuelo, "Total horas de vuelo", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :horas_vuelo, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :toque_y_despegue, "Operaciones de toques y despegues", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :toque_y_despegue, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :aterrizajes, "Aterrizajes finales", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.number_field :aterrizajes, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :aerodromos, "Aeródromo de operaciones", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :aerodromos, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.label :incidentes, class: "flex justify-between items-center" do %>
      <div class="flex flex-col">
        <span class="text-sm font-medium text-gray-900 dark:text-gray-300">Reportar incidente</span>
        <span class="text-sm font-light text-gray-600 dark:text-gray-300">Nemo enim ipsam voluptatem quia voluptas sit aspernatur.</span>
      </div>
      <div class="relative inline-flex items-center cursor-pointer">
        <%= form.check_box :incidentes, class: "sr-only peer" %>
        <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
      </div>
    <% end %>
  </div>

  <div class="mb-6">
    <%= form.label :comentarios, "Detalle incidente", class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_area :comentarios, rows: 4, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div>

    <%= form.submit "Enviar", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </div>
<% end %>

app/views/operaciones_aereas/_operaciones_aerea.html.erb
<div id="<%= dom_id operaciones_aerea %>">
  <p>
    <strong>Aeronave:</strong>
    <%= operaciones_aerea.aeronave_id %>
  </p>

  <p>
    <strong>Piloto:</strong>
    <%= operaciones_aerea.piloto_id %>
  </p>

  <p>
    <strong>Fecha operacion:</strong>
    <%= operaciones_aerea.fecha_operacion %>
  </p>

  <p>
    <strong>Horas vuelo:</strong>
    <%= operaciones_aerea.horas_vuelo %>
  </p>

  <p>
    <strong>Toque y despegue:</strong>
    <%= operaciones_aerea.toque_y_despegue %>
  </p>

  <p>
    <strong>Aterrizajes:</strong>
    <%= operaciones_aerea.aterrizajes %>
  </p>

  <p>
    <strong>Incidentes:</strong>
    <%= operaciones_aerea.incidentes %>
  </p>

  <p>
    <strong>Comentarios:</strong>
    <%= operaciones_aerea.comentarios %>
  </p>

  <p>
    <strong>Aerodromos:</strong>
    <%= operaciones_aerea.aerodromos %>
  </p>

</div>

app/views/operaciones_aereas/edit.html.erb
<h1>Editing operaciones aerea</h1>

<%= render "form", operaciones_aerea: @operaciones_aerea %>

<br>

<div>
  <%= link_to "Show this operaciones aerea", @operaciones_aerea %> |
  <%= link_to "Back to operaciones aereas", operaciones_aereas_path %>
</div>

app/views/operaciones_aereas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Operaciones aereas</h1>

<div id="operaciones_aereas">
  <% @operaciones_aereas.each do |operaciones_aerea| %>
    <%= render operaciones_aerea %>
    <p>
      <%= link_to "Show this operaciones aerea", operaciones_aerea %>
    </p>
  <% end %>
</div>

<%= link_to "New operaciones aerea", new_operaciones_aerea_path %>

app/views/operaciones_aereas/new.html.erb
<div class="md:flex md:flex-row">
  <div class="flex flex-col justify-start mb-10 md:basis-1/3">
    <h1 class="text-xl font-bold mb-2">Registro de operaciones aéreas</h1>
    <!--<h2 class="text-sm mb-2">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </h2>-->
  </div>

  <div class="md:basis-1/2">
    <%= render "form", operaciones_aerea: @operaciones_aerea %>

  </div>
</div>

app/views/operaciones_aereas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operaciones_aerea %>

<div>
  <%= link_to "Edit this operaciones aerea", edit_operaciones_aerea_path(@operaciones_aerea) %> |
  <%= link_to "Back to operaciones aereas", operaciones_aereas_path %>

  <%= button_to "Destroy this operaciones aerea", @operaciones_aerea, method: :delete %>
</div>